spring.application.name=kalisys
spring.datasource.url=jdbc:
spring.datasource.username=postegresql://localhost:5432/academia
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyaway.locations=classpath:db/migration